- hosts: all

  vars:
    cmatrix_git_repo: https://github.com/abishekvashok/cmatrix.git
    work_dir: /tmp/cmatrix

  tasks:
    - name: Delete working directory
      become: yes
      file:
        path: '{{ work_dir }}'
        state: absent

    - name: Make working directory
      become: yes
      file:
        path: '{{ work_dir }}'
        state: directory
        mode: 0755

    - name: Install required packages
      become: yes
      yum:
        name: '{{ item }}'
        state: present
      loop:
        - '@Development Tools'
        - libyaml-devel
        - ncurses-devel

    - name: Download cmatrix install file
      become: yes
      git:
        repo: '{{ cmatrix_git_repo }}'
        dest: '{{ work_dir }}'
        force: yes

    - name: Build cmatrix 1 / autoreconf -i
      become: yes
      command: autoreconf -i
      args:
        chdir: '{{ work_dir }}'

    - name: Build cmatrix 2 / .configure
      become: yes
      command: ./configure
      args:
        chdir: '{{ work_dir }}'

    - name: Build cmatrix 3 / make
      become: yes
      make:
        chdir: '{{ work_dir }}'

    - name: Build cmatrix 4 / make install
      become: yes
      make:
        chdir: '{{ work_dir }}'
        target: install
