- hosts: all

  vars:
    cmatrix_git_repo: https://github.com/abishekvashok/cmatrix.git

  tasks:
    - name: Install Development Tools with yum
      become: yes
      yum:
        name: '@Development Tools'
        state: present
    
    - name: Install libyaml with yum
      become: yes
      yum:
        name: libyaml-devel
        state: present
    
    - name: Install ncurses-devel with yum
      become: yes
      yum:
        name: ncurses-devel
        state: present
    
    - name: download cmatrix install file
      become: yes
      git:
        repo: '{{ cmatrix_git_repo }}' 
        dest: /tmp/cmatrix
        force: yes
    
    - name: Build cmatrix 1 / autoreconf -i 
      become: yes
      command: autoreconf -i 
      args:
        chdir: /tmp/cmatrix
    
    - name: Build cmatrix 2 / .configure
      become: yes
      command: ./configure
      args:
        chdir: /tmp/cmatrix
    
    - name: Build cmatrix 3 / make
      become: yes
      make:
        chdir: /tmp/cmatrix
    
    - name: Build cmatrix 4 / make install
      become: yes
      make:
        chdir: /tmp/cmatrix
        target: install
