steps: &steps
  steps:
    - checkout
    - ansible/ansible-lint:
        reponame: ansible_joke-programs_cmatrix
    - ansible/ansible-playbook:
        reponame: ansible_joke-programs_cmatrix
    - run:
        name: Show CMatrix version
        command: cmatrix -V

version: 2.1

orbs:
  ansible: orbss/ansible@volatile

jobs:
  ansible-yum:
    executor:
      name: ansible/centos7-ansible-yum
    working_directory: /tmp/ansible
    <<: *steps
  ansible-stable:
    executor:
      name: ansible/centos7-ansible-stable
    working_directory: /tmp/ansible
    <<: *steps
  ansible-devel:
    executor:
      name: ansible/centos7-ansible-devel
    working_directory: /tmp/ansible
    <<: *steps

workflows:
  version: 2
  excute-playbook:
    jobs:
      - ansible-yum
      - ansible-stable
      - ansible-devel
