steps: &steps
  steps:
    - ansible/retrieve-playbook:
        reponame: ansible_joke-programs_cmatrix
    - ansible/ansible-lint:
        reponame: ansible_joke-programs_cmatrix
    - ansible/ansible-playbook:
        reponame: ansible_joke-programs_cmatrix
    - run:
        name: Show CMatrix version
        command: cmatrix -V

version: 2.1

orbs:
  ansible: orbss/ansible@0.1.0

jobs:
  ansible-yum:
    executor:
      name: ansible/ansible-yum
    <<: *steps
  ansible-stable:
    executor:
      name: ansible/ansible-stable
    <<: *steps
  ansible-devel:
    executor:
      name: ansible/ansible-devel
    <<: *steps

workflows:
  version: 2
  excute-playbook:
    jobs:
      - ansible-yum:
          filters:
            branches:
              only: topic
      - ansible-stable:
          filters:
            branches:
              only: topic
      - ansible-devel:
          filters:
            branches:
              only: topic
