---
- name: Verify
  hosts: all

  tasks:
    - name: Check whether CMatrix is installed
      ansible.builtin.command: cmatrix -V
      register: CMatrix_VERSION
      changed_when: false

    - name: Check OS version
      ansible.builtin.command: cat /etc/redhat-release
      register: OS_VERSION
      changed_when: false

    - name: Show Hugo version
      ansible.builtin.debug:
        var: CMatrix_VERSION

    - name: Show OS version
      ansible.builtin.debug:
        var: OS_VERSION
